import type { PendingSampleOrder, ShippingHistory } from './types';

export const MOCK_PENDING_ORDERS: PendingSampleOrder[] = [
  {
    id: '1',
    order_number: 'SO-20250829-001',
    npc_number: '227/NPC/SKH/2025',
    order_type: 'sample',
    sample_type: 'JET-A1',
    vessel_name: 'MT. Commodore One',
    tank_number: 'Tangki 107',
    quantity: 4,
    unit: 'botol',
    pickup_location: 'Tanjung Priok Port, Jakarta',
    delivery_location: 'LPUJ Laboratory, Priok',
    estimated_arrival_time: '2025-08-29T15:00:00',
    notes: 'Prioritaskan pengantaran ke LPUJ segera.',
    priority: 'urgent',
    created_at: '2025-08-29T08:30:00',
  },
  {
    id: '2',
    order_number: 'RQ-20250829-002',
    npc_number: '228/NPC/SKH/2025',
    order_type: 'request',
    sample_type: 'Avgas',
    vessel_name: 'MT. Pioneer',
    tank_number: 'Tangki 203',
    quantity: 3,
    unit: 'botol',
    pickup_location: 'Anchorage Area B, Jakarta Bay',
    delivery_location: 'Lemigas Laboratory, Jakarta',
    estimated_arrival_time: '2025-08-29T17:30:00',
    notes: 'Pastikan lampirkan form penerimaan.',
    priority: 'normal',
    created_at: '2025-08-29T10:15:00',
  },
  {
    id: '3',
    order_number: 'SO-20250829-003',
    npc_number: '229/NPC/SKH/2025',
    order_type: 'ready',
    sample_type: 'Soft blended',
    vessel_name: 'MT. Ocean Star',
    tank_number: 'Tangki 301',
    quantity: 2,
    unit: 'botol',
    pickup_location: 'Tanjung Priok Port, Jakarta',
    delivery_location: 'Balongan Testing Center',
    estimated_arrival_time: '2025-08-30T00:00:00',
    notes: 'Pengiriman malam hari, koordinasi dengan keamanan.',
    priority: 'urgent',
    created_at: '2025-08-29T11:45:00',
  },
  {
    id: '4',
    order_number: 'RQ-20250829-004',
    npc_number: '230/NPC/SKH/2025',
    order_type: 'request',
    sample_type: 'JET-A1',
    vessel_name: 'MT. Excellence',
    tank_number: 'Tangki 108',
    quantity: 5,
    unit: 'botol',
    pickup_location: 'Private Port, Bekasi',
    delivery_location: 'LPUJ Laboratory, Priok',
    estimated_arrival_time: '2025-08-29T22:00:00',
    notes: 'Jadwalkan ulang bila hujan deras.',
    priority: 'normal',
    created_at: '2025-08-29T12:20:00',
  },
];

export const MOCK_HISTORY_ORDERS: ShippingHistory[] = [
  {
    id: '1',
    order_number: 'SO-20250828-015',
    npc_number: '224/NPC/SKH/2025',
    sample_type: 'Soft blended',
    pickup_location: 'Tanjung Priok Port',
    delivery_location: 'LPUJ Laboratory',
    pickup_time: '2025-08-28 09:30',
    delivery_time: '2025-08-28 10:45',
    status: 'completed',
    distance: '15 km',
    vessel_name: 'MT. Southern Star',
    tank_number: 'Tangki 205',
    quantity: 3,
    unit: 'botol',
    status_updates: [
      {
        id: '1',
        timestamp: '2025-08-28 09:30:00',
        message:
          'Order diambil oleh driver, menuju lokasi pickup: Tanjung Priok Port',
        created_by: 'Driver',
      },
      {
        id: '2',
        timestamp: '2025-08-28 09:45:00',
        message:
          'Sample berhasil diambil dari Tanjung Priok Port, menuju ke LPUJ Laboratory',
        created_by: 'System',
      },
      {
        id: '3',
        timestamp: '2025-08-28 10:15:00',
        message: 'Tiba di lokasi delivery, sedang melakukan handover sample',
        created_by: 'Driver',
      },
    ],
  },
  {
    id: '2',
    order_number: 'RQ-20250827-008',
    npc_number: '225/NPC/SKH/2025',
    sample_type: 'JET-A1',
    pickup_location: 'Anchorage Area A',
    delivery_location: 'Balongan Testing Center',
    pickup_time: '2025-08-27 08:00',
    delivery_time: '2025-08-27 14:30',
    status: 'completed',
    distance: '380 km',
    vessel_name: 'MT. Eagle Express',
    tank_number: 'Tangki 401',
    quantity: 5,
    unit: 'botol',
    status_updates: [
      {
        id: '1',
        timestamp: '2025-08-27 08:00:00',
        message:
          'Order diambil oleh driver, menuju lokasi pickup: Anchorage Area A',
        created_by: 'Driver',
      },
      {
        id: '2',
        timestamp: '2025-08-27 08:30:00',
        message:
          'Sample berhasil diambil dari Anchorage Area A, menuju ke Balongan Testing Center',
        created_by: 'System',
      },
      {
        id: '3',
        timestamp: '2025-08-27 11:15:00',
        message: 'Istirahat di rest area Tol Cipali, perjalanan lancar',
        created_by: 'Driver',
      },
      {
        id: '4',
        timestamp: '2025-08-27 13:45:00',
        message: 'Tiba di Balongan Testing Center, melakukan proses delivery',
        created_by: 'Driver',
      },
    ],
  },
  {
    id: '3',
    order_number: 'SO-20250826-012',
    npc_number: '226/NPC/SKH/2025',
    sample_type: 'Avgas',
    pickup_location: 'Private Port',
    delivery_location: 'Lemigas Laboratory',
    pickup_time: '2025-08-26 11:00',
    delivery_time: '2025-08-26 11:00',
    status: 'cancelled',
    distance: '20 km',
    vessel_name: 'MT. Swift Runner',
    tank_number: 'Tangki 102',
    quantity: 2,
    unit: 'botol',
    status_updates: [
      {
        id: '1',
        timestamp: '2025-08-26 11:00:00',
        message:
          'Order diambil oleh driver, menuju lokasi pickup: Private Port',
        created_by: 'Driver',
      },
      {
        id: '2',
        timestamp: '2025-08-26 11:30:00',
        message:
          'Tidak dapat mengakses kapal karena masalah keamanan pelabuhan',
        created_by: 'Driver',
      },
      {
        id: '3',
        timestamp: '2025-08-26 11:45:00',
        message: 'Order dibatalkan atas permintaan management port',
        created_by: 'System',
      },
    ],
  },
  {
    id: '4',
    order_number: 'SO-20250825-009',
    npc_number: '221/NPC/SKH/2025',
    sample_type: 'Diesel',
    pickup_location: 'Tanjung Priok Port',
    delivery_location: 'LPUJ Laboratory',
    pickup_time: '2025-08-25 14:15',
    delivery_time: '2025-08-25 15:30',
    status: 'completed',
    distance: '15 km',
    vessel_name: 'MT. Ocean Breeze',
    tank_number: 'Tangki 310',
    quantity: 4,
    unit: 'botol',
    status_updates: [
      {
        id: '1',
        timestamp: '2025-08-25 14:15:00',
        message:
          'Order diambil oleh driver, menuju lokasi pickup: Tanjung Priok Port',
        created_by: 'Driver',
      },
      {
        id: '2',
        timestamp: '2025-08-25 14:45:00',
        message:
          'Sample berhasil diambil dari Tanjung Priok Port, menuju ke LPUJ Laboratory',
        created_by: 'System',
      },
    ],
  },
  {
    id: '5',
    order_number: 'RQ-20250824-004',
    npc_number: '222/NPC/SKH/2025',
    sample_type: 'JET-A1',
    pickup_location: 'Anchorage Area B',
    delivery_location: 'Lemigas Laboratory',
    pickup_time: '2025-08-24 10:30',
    delivery_time: '2025-08-24 11:45',
    status: 'completed',
    distance: '25 km',
    vessel_name: 'MT. Blue Horizon',
    tank_number: 'Tangki 205',
    quantity: 3,
    unit: 'botol',
    status_updates: [
      {
        id: '1',
        timestamp: '2025-08-24 10:30:00',
        message:
          'Order diambil oleh driver, menuju lokasi pickup: Anchorage Area B',
        created_by: 'Driver',
      },
      {
        id: '2',
        timestamp: '2025-08-24 11:00:00',
        message:
          'Sample berhasil diambil dari Anchorage Area B, menuju ke Lemigas Laboratory',
        created_by: 'System',
      },
      {
        id: '3',
        timestamp: '2025-08-24 11:20:00',
        message:
          'Sedikit terkendala traffic, estimasi tiba 15 menit lebih lambat',
        created_by: 'Driver',
      },
    ],
  },
  {
    id: '6',
    order_number: 'SO-20250823-016',
    npc_number: '223/NPC/SKH/2025',
    sample_type: 'Avgas',
    pickup_location: 'Private Port, Bekasi',
    delivery_location: 'Balongan Testing Center',
    pickup_time: '2025-08-23 07:00',
    delivery_time: '2025-08-23 13:30',
    status: 'completed',
    distance: '420 km',
    vessel_name: 'MT. Sky Rider',
    tank_number: 'Tangki 501',
    quantity: 6,
    unit: 'botol',
    status_updates: [
      {
        id: '1',
        timestamp: '2025-08-23 07:00:00',
        message:
          'Order diambil oleh driver, menuju lokasi pickup: Private Port, Bekasi',
        created_by: 'Driver',
      },
      {
        id: '2',
        timestamp: '2025-08-23 07:45:00',
        message:
          'Sample berhasil diambil dari Private Port, Bekasi, menuju ke Balongan Testing Center',
        created_by: 'System',
      },
      {
        id: '3',
        timestamp: '2025-08-23 10:15:00',
        message:
          'Perjalanan lancar, melewati Tol Cipali dengan kondisi cuaca cerah',
        created_by: 'Driver',
      },
      {
        id: '4',
        timestamp: '2025-08-23 12:30:00',
        message: 'Hampir tiba di Balongan Testing Center, estimasi 1 jam lagi',
        created_by: 'Driver',
      },
    ],
  },
  {
    id: '7',
    order_number: 'RQ-20250822-007',
    npc_number: '220/NPC/SKH/2025',
    sample_type: 'Soft blended',
    pickup_location: 'Tanjung Priok Port',
    delivery_location: 'LPUJ Laboratory',
    pickup_time: '2025-08-22 16:00',
    delivery_time: '2025-08-22 16:00',
    status: 'cancelled',
    distance: '15 km',
  },
  {
    id: '8',
    order_number: 'SO-20250821-013',
    npc_number: '219/NPC/SKH/2025',
    sample_type: 'JET-A1',
    pickup_location: 'Anchorage Area C',
    delivery_location: 'Lemigas Laboratory',
    pickup_time: '2025-08-21 09:15',
    delivery_time: '2025-08-21 10:30',
    status: 'completed',
    distance: '30 km',
  },
  {
    id: '9',
    order_number: 'RQ-20250820-002',
    npc_number: '218/NPC/SKH/2025',
    sample_type: 'Diesel',
    pickup_location: 'Private Port, Jakarta',
    delivery_location: 'Balongan Testing Center',
    pickup_time: '2025-08-20 11:45',
    delivery_time: '2025-08-20 18:15',
    status: 'completed',
    distance: '390 km',
  },
  {
    id: '10',
    order_number: 'SO-20250819-010',
    npc_number: '217/NPC/SKH/2025',
    sample_type: 'Avgas',
    pickup_location: 'Tanjung Priok Port',
    delivery_location: 'LPUJ Laboratory',
    pickup_time: '2025-08-19 13:30',
    delivery_time: '2025-08-19 14:45',
    status: 'completed',
    distance: '15 km',
  },
];
